# BukkitTelnet v4.2 Configuration File

# Address to listen on, leave blank for all
address: ''

# Port to bind to:
port: 8765

# Main connection password, must be defined
password: 'tom'

# List of admins / IPs that don't have to use the password
admins:
  prozza:
    - 176.56.237.227
  tomcreeper:
    - 123.917.128
  
